app = "tanaki-open-souls"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    type = "tcp"

[[vm]]
  memory = "4gb"
  cpu_kind = "performance"
  cpus = 2

[metrics]
  port = 9091
  path = "/metrics"

[[mounts]]
  source = "tanaki_data"
  destination = "/app/data"

