app = "new-miyu-soul-app"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"
  
[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_002
min_machines_running = 0
processes = [ "app" ]

[[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    type = "tcp"

[[vm]]
  memory = "4gb"
  cpu_kind = "performance"
  cpus = 2

[metrics]
  port = 9091
  path = "/metrics"

[[mounts]]
  source = "tanaki_data"
  destination = "/app/data"
